### ISSUE TITLE
Bugs on the README of private docker registry.

### ISSUE THREAD

**Issue by huajunzhao** [Azure/devops-sample-solution-for-azure-china#32]
`$ bash ./config-insecure-registry.sh -r <registry_fqdn> -r <k8s_master_fqdn> -u <k8s_ssh_user> -k <path_to_id_rsa>`

it should be 

`$ bash ./config-insecure-registry.sh -r <registry_fqdn> -m <k8s_master_fqdn> -u <k8s_ssh_user> -k <path_to_id_rsa>`

**Comment by andyzhangx** [comment]
I have fixed the doc, thanks for reporting.
